englercj/tsd-jsdoc

publish.js

This is supplied if you pass `-P package.json`, and currently causes `module undefined {}` to show up at the bottom of all generated files. It's not necessary.
(BTW, this project is awesome.)

Disable 'package' doclet

---

src/publish.ts

This was always returning `undefined` if `outFile` was set. Parentheses fixes the issue.

Parentheses needed to disambiguate outFile option

---

src/publish.ts

Hi,
I ran into an issue running this JSDoc template on one of my packages where the TS definition couldn't be created. The `src/publish.ts` file creates the TS definition and gives it a name that matches the `name` prop from a given package's `package.json` file and places it in the `docs/` directory. Normally that works fine, however for private-scoped packages this doesn't work because `fs.writeFileSync()` won't create the full nested file path.
There's probably a couple of options to solve that:
* Use a combination of `fs.existsSync('docs/@my-scope')` followed by `fs.mkdirSync('docs/@myscope')` prior to writing `docs/@my-scope/package-name.d.ts`
* Get rid of the leading `@my-scope/` prefix from the pacakge's name when writing `docs/package-name.d.ts`
That last option seems sensible to …

fix 'No such file or directory' error when creating definition for private-scoped packages

---

src/type_resolve_helpers.ts
test/expected/class_all.d.ts
test/fixtures/class_all.js

2 things here, let me know and I can split them.
1) Complex types like a union that had a generic, or a generic that had a union could not be resolved, ex: Promise<Array.<*>|Object|number|string>
2) We like to document our promise resolve and rejection types separated with a comma, ex: Promise<ResolveType, RejectType>.  There doesn't seem to be consensus on exactly how do to this based on this still open feature request: https://github.com/jsdoc3/jsdoc/issues/509.  Typescript does not define the RejectType of a promise it is always 'any', see: https://github.com/Microsoft/TypeScript/issues/7588.  Due to this I've added a workaround that removes the second type when parsing a Promise.
Thanks btw,
- Gord

resolve complex types and workaround promise reject types

---

src/type_resolve_helpers.ts
test/expected/class_all.d.ts
test/fixtures/class_all.js

Adds object handling to resolveComplexTypeName, Fixes: #65
Note: for #65 there must be a space after the colon in the object definition or jsdoc doesn't parse it correctly.
```
// Bad:
newChannels:Channel[]
// Good:
newChannels: Channel[]
```

Support objects in complex types, Fixes: #65

---

src/type_resolve_helpers.ts
test/expected/class_all.d.ts
test/expected/typedef_all.d.ts
test/fixtures/class_all.js
test/fixtures/typedef_all.js

Adds function support to complex type lookups.  Not sure how you feel about the auto-generated "arg0" names, ex:
promiseLotsArgsFunc(): Promise<(arg0: OtherThing[], arg1: object, arg2: number, arg3: etc
But I copied the typescript in their handling of this.  Also I think it will be a rare case where you would return a function that takes multiple arguments.
Let me know what you think.

Add function support to complex types

---

src/create_helpers.ts
test/expected/enum_all.d.ts

Set Enum keys and values instead keys only. It is useful to see what value will be use.
**Before:**
**After:**

set enum declaration values

---

src/type_resolve_helpers.ts
test/expected/class_all.d.ts
test/expected/function_all.d.ts
test/fixtures/class_all.js
test/fixtures/function_all.js

Fixes support for jsdoc's standalone `Array` keyword as can be seen in examples such as:
```javascript
/**
* Returns the sum of a and b
* @param {number} a
* @param {number} b
* @param {boolean} retArr If set to true, the function will return an array
* @returns {(number|Array)} Sum of a and b or an array that contains a, b and the sum of a and b.
*/
function sum(a, b, retArr) {
if (retArr) {
return [a, b, a + b];
}
return a + b;
}
```
Source: https://jsdoc.app/tags-returns.html
Without this PR, `tsd-jsdoc` will generate invalid typescript (because outputting just `Array` will conflict with the built-in generic interface `Array<T>` ).

support for simple Array type

---

src/create_helpers.ts
test/expected/property_all.d.ts
test/fixtures/property_all.js
test/specs/property.ts

We need support for class properties and since #73 has not been updated since May. I decided to take it upon myself to fulfill the requirement regarding tests, as stated in https://github.com/englercj/tsd-jsdoc/pull/73#issuecomment-493285402.
So this PR is based on the work done by @HackbrettXXX, with the addition of test cases. See output: https://travis-ci.org/englercj/tsd-jsdoc/builds/575963771#L251

support for @property on classes (including tests)

---

src/create_helpers.ts
src/type_resolve_helpers.ts
src/typings/jsdoc.d.ts
test/expected/class_all.d.ts
test/expected/interface_all.d.ts
test/fixtures/class_all.js
test/fixtures/interface_all.js

Currently, there is no way to declare an optional method or member in a class or interface (which is quite useful in TypeScript). This PR adds support for it by allowing the method or member name to be wrapped in brackets (`[myMethod]` or `[myMember]`) to indicate it is optional - just like with parameters.

support optional methods and members

---

src/create_helpers.ts
test/expected/namespace_all.d.ts
test/fixtures/namespace_all.js

This PR adds proper support for constant declarations in a namespace. Without it, the `d.ts` output will just be a regular non-constant variable. Additionally, if the constant has a default or literal value, it will be included in the declaration (because it is more actionable type information).

support @constant in a namespace

---

src/Emitter.ts
test/expected/interface_all.d.ts
test/fixtures/interface_all.js

JSDoc allows members (like functions and variables) to be static inside an interface (or mixin). Currently, this will generate invalid TypeScript. This PR fixes that by moving all static members to a namespace (which has the same name as the interface) and thus performs a namespace merge.
So the following JavaScript:
```javascript
/**
* @interface
*/
function Color() {}
/**
* @function Color.staticMethod1
* @static
*/
Color.staticMethod = function() {};
/**
* @member {Number}
* @static
*/
Color.staticMember = 1;
/**
* @function
*/
Color.prototype.instanceMethod = function() {};
/**
* @member {Number}
*/
Color.prototype.instanceMember = 2;
```
Will generate the following TypeScript:
```typescript
declare namespace Color {
/**
* @function
* @static
*/
function staticMethod(): void;
/**
* …
```

support static members/methods in an interface

---

package-lock.json
package.json
test/expected/class_all.d.ts
test/fixtures/class_all.js
test/lib/conf.json
test/lib/index.ts
test/lib/plugin.js

Resolves #101.
There was an issue with type applications in Node 12 which was fixed in [this commit to jsdoc](https://github.com/jsdoc/jsdoc/commit/dc9d5afe72a3039137e7a49c311473ed25e78445).
This PR upgrades `jsdoc` and `jsdoc-api`. However, this `jsdoc` upgrade introduces some changes to the output:
* Most of the Closure Compiler tags were added to the list of definitions at some point, but in such a way that the are ignored. I've added a simple plugin which adds `@template` to the list of tags in jsdoc output. This means users need to use a similar plugin to achieve `@template` support. There might a better solution.
* Classes and constructors are being merged in strange ways and `@class` tags without a name results in the class being considered `undocumented` which in turn means it …

Upgrade jsdoc(api) and fix tests

---

src/logger.ts

The error messages are missing source locations for ease of navigating. This PR add to every logged error: Source filename (not the path), line number, and column number:
```
[TSD-JSDoc] dataset.js:619:4 Failed to find parent of doclet 'DatasetLocal#_getItemIndexes' using memberof 'DatasetLocal', this is likely due to invalid JSDoc.
[TSD-JSDoc] dataset.js:630:4 Failed to find parent of doclet 'DatasetLocal#_readAndParseFile' using memberof 'DatasetLocal', this is likely due to invalid JSDoc.
[TSD-JSDoc] stealth.js:40:0 Failed to find parent of doclet 'module.exports' using memberof 'module', this is likely due to invalid JSDoc.
[TSD-JSDoc] autoscaled_pool.js:209:4 Unable to resolve type for AutoscaledPool#minConcurrency, none specified in JSDoc. Defaulting to `any`.
```
Please review and …

resolves #113 Added source location information to warnings

---

.vscode/launch.json
README.md
jsdoc-conf.json
package.json
src/plugin.ts
src/typings/jsdoc.d.ts
test/lib/conf.json
test/lib/index.ts

PR changes:
- Move `test/lib/plugin.js` to `src/plugin.ts`
- Move `test/lib/conf.json` to `jsdoc-conf.json`
- Add necessary jsdoc API declarations for `plugin.ts`
- Add documentation for how to enable plugin's `@template` support
- Make sure source is rebuilt before running tests
- Add launch settings for vscode to allow debugging

Improve documentation, building, and debugging

---

src/Emitter.ts
src/create_helpers.ts
src/doclet_utils.ts
src/typings/jsdoc.d.ts
test/expected/enum_all.d.ts

Cleanup some TS checks from #115 and refactor doclet type getters into a separate file.
This removes all the `'string' in obj` checks and usages of `obj['string']`.
Fixes #111.

Resolves #111 preserve comment on enum members

---

src/publish.ts
src/typings/jsdoc.d.ts
test/expected/class_all.d.ts
test/fixtures/class_all.js

Fixes #125 
PR changes:
- Add test for inherited members (that fail without fix)
- Filter out inherited non-overridden members and fix failing test

Filter out inherited non-overridden members

---

package-lock.json
package.json
test/expected/namespace_all.d.ts
test/fixtures/namespace_all.js
test/lib/index.ts
test/lib/jsdoc-api.d.ts
test/lib/jsdoc-api.js
test/lib/render.ts
test/typings/jsdoc-api.d.ts

Currently, all logging in the library is silently discarded when running the tests. Which makes detecting issues and debugging unnecessarily a lot harder. The PR fixes this by making the following changes:
1. When tests spawn a jsdoc child process (via `jsdoc-api`), configure spawn so that stdio is inherited.
2. Because `jsdoc-api` doesn't provide a way to configure the spawn in the main API, use lower-level APIs. This is what the new file `jsdoc-api.js` does (and `jsdoc-api.d.ts` provides typings for).
3. Remove the old `jsdoc-api.d.ts`, which is no longer needed.
As a bonus, I also fixed the following warning that otherwise wouldn't show up in `Namespace Checks`:
```
[TSD-JSDoc] Unable to resolve type for an unnamed item, this is likely due to invalid JSDoc.
Often this is caused by …
```

Enable console logging for tests

---

README.md
src/plugin.ts
test/expected/typeof_all.d.ts
test/fixtures/typeof_all.js
test/specs/typeof.ts

Fixes #129
PR changes:
- Add support for converting `typeof T` ([as supported by CC](https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System#the-javascript-type-language) and [eslint for jsdoc](https://github.com/gajus/eslint-plugin-jsdoc)) into `Class<T>`.
- Add the same tests for both `Class<T>` and `typeof T` to make sure results are equivalent.
- Update readme to reflect support for `typeof T`.

Add support for ClosureCompiler syntax "typeof T"

---

src/create_helpers.ts
src/type_resolve_helpers.ts
test/expected/typedef_all.d.ts

Given the following JSDoc
```js
/**
* @typedef {Object} BillboardGraphics.ConstructorOptions
*
* Initialization options for the BillboardGraphics constructor
*
* @property {Property | boolean} [show=true] A boolean Property specifying the visibility of the billboard.
*/
```
tsd-jsdoc was producing the following TS code
```ts
/**
* Initialization options for the BillboardGraphics constructor
* @property [show = true] - A boolean Property specifying the visibility of the billboard.
*/
type ConstructorOptions = {
show?: Property | boolean;
};
```
`@property` is not valid TS markup and the actual property, show, does not include its description or default value.
After this change the same JSDoc markup produces much nicer code that handles both of these:
```ts
/**
* Initialization options for …
```

Better support for typedef @property
